# Generated by Django 3.2.5 on 2021-07-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programas_instalados',
            old_name='version',
            new_name='versio',
        ),
    ]
