# Generated by Django 3.2.5 on 2021-07-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_rename_versio_programas_instalados_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas_instalados',
            name='cantidad_programas',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad-programas'),
        ),
        migrations.AddField(
            model_name='programas_instalados',
            name='pc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.pc_farmacia'),
        ),
    ]
