# Generated by Django 3.2.5 on 2021-07-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_auto_20210713_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas_instalados',
            name='cantidad_programas',
        ),
        migrations.AlterField(
            model_name='programas_instalados',
            name='fecha_install',
            field=models.CharField(max_length=256, verbose_name='Fecha de isntalación'),
        ),
        migrations.CreateModel(
            name='Cantidad_Programas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='cantidad de programas')),
                ('tabla_programas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.programas_instalados')),
            ],
            options={
                'verbose_name': 'cantidad_programas',
            },
        ),
    ]
