# Generated by Django 3.2.5 on 2021-07-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_auto_20210713_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas_instalados',
            name='fecha_install',
            field=models.DateField(),
        ),
    ]
