# Generated by Django 3.2.5 on 2021-07-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_alter_programas_instalados_fecha_install'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas_instalados',
            name='fecha_install',
            field=models.CharField(max_length=256, verbose_name='Fecha de isntalación'),
        ),
    ]
