# Generated by Django 3.2.5 on 2021-07-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_alter_programas_instalados_fecha_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas_instalados',
            name='fecha_rel',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha-Relevamiento'),
        ),
    ]
