# Generated by Django 3.2.3 on 2021-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_alter_programa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Desactivar'), (1, 'activar')], default=1),
        ),
    ]
