# Generated by Django 3.2.3 on 2021-06-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_alter_provincia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Activar'), (1, 'Desactivar')], default=1),
        ),
    ]
