# Generated by Django 3.2.3 on 2021-06-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_localidad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='descripcion',
            field=models.CharField(choices=[(1, 'Corrientes'), (2, 'Chaco'), (3, 'Bs. As.'), (4, 'Salta'), (5, 'Tucuman'), (6, 'Santiago del Estero'), (7, 'Jujuy'), (8, 'San Luis'), (9, 'Entre Ríos'), (10, 'Catamarca'), (11, 'Chubut'), (12, 'Córdoba'), (13, 'Formosa'), (14, 'La Pampa'), (15, 'La Rioja'), (16, 'Mendoza'), (17, 'Misiones'), (18, 'Neuquén'), (19, 'Río Negro'), (20, 'San Juan'), (21, 'Santa Cruz'), (22, 'Santa Fe'), (23, 'Tierra del Fuego')], default=1, max_length=256),
        ),
    ]
