# Generated by Django 3.2.3 on 2021-06-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0012_auto_20210624_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='id_provincia',
            field=models.ForeignKey(choices=[(1, 'Corrientes'), (2, 'Chaco'), (3, 'Bs. As.'), (4, 'Salta'), (5, 'Tucuman'), (6, 'Santiago del Estero'), (7, 'Jujuy'), (8, 'San Luis'), (9, 'Entre Ríos'), (10, 'Catamarca'), (11, 'Chubut'), (12, 'Córdoba'), (13, 'Formosa'), (14, 'La Pampa'), (15, 'La Rioja'), (16, 'Mendoza'), (17, 'Misiones'), (18, 'Neuquén'), (19, 'Río Negro'), (20, 'San Juan'), (21, 'Santa Cruz'), (22, 'Santa Fe'), (23, 'Tierra del Fuego')], on_delete=django.db.models.deletion.CASCADE, to='farmacia.provincia'),
        ),
    ]
