# Generated by Django 3.2.3 on 2021-06-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_alter_localidad_id_provincia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localidad',
            old_name='id_provincia',
            new_name='id_provincia_id',
        ),
    ]
