# Generated by Django 3.2.3 on 2021-07-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0014_rename_id_provincia_localidad_id_provincia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_farmacia',
            name='RAM_procentaje_disponible',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='RAM_disponible'),
        ),
        migrations.AddField(
            model_name='pc_farmacia',
            name='procentaje_disponible_C',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='porcentaje_disponible_C'),
        ),
        migrations.AddField(
            model_name='pc_farmacia',
            name='procentaje_disponible_D',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='porcentaje_disponible_D'),
        ),
        migrations.AddField(
            model_name='pc_farmacia',
            name='version_so',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activar'), (0, 'Desactivar')], default=1),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id_provincia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.provincia'),
        ),
    ]
