# Generated by Django 3.2.2 on 2021-05-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('fica_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Fcia')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
            ],
        ),
    ]
