# Generated by Django 3.2.2 on 2021-06-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_auto_20210518_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Programa')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Programa')),
                ('fecha_install', models.DateField()),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
    ]
