# Generated by Django 3.2.3 on 2021-06-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_provincia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='estado'),
        ),
    ]
