# Generated by Django 3.2.3 on 2021-06-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_programa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcia',
            name='ip',
            field=models.ForeignKey(blank=True, default='192.168.0.', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.pc_farmacia'),
        ),
    ]
