# Generated by Django 3.2.3 on 2021-06-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_alter_fcia_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Desactivar'), (1, 'Activar')], default=1),
        ),
    ]
