# Generated by Django 3.2.2 on 2021-05-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc_Farmacia',
            fields=[
                ('ip', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='IP')),
                ('nombre_pc', models.CharField(max_length=256, verbose_name='nombre_pc')),
                ('ip_publica', models.CharField(max_length=256, verbose_name='ip_publica')),
                ('arquitectura_so', models.CharField(max_length=256, verbose_name='arquitectura_so')),
                ('tipo_maquina', models.CharField(max_length=256, verbose_name='tipo_maquina')),
                ('procesador', models.CharField(max_length=256, verbose_name='procesador')),
                ('cores_fisicos', models.IntegerField(verbose_name='cores_fisicos')),
                ('cores_totales', models.IntegerField(verbose_name='cores_totales')),
                ('RAM_tot', models.CharField(max_length=256, verbose_name='ram_total')),
                ('RAM_usada', models.CharField(max_length=256, verbose_name='ram_usada')),
                ('RAM_disponible', models.CharField(max_length=256, verbose_name='ram_disponible')),
                ('espacio_tot_C', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_total_C')),
                ('espacio_tot_D', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_total_D')),
                ('espacio_usado_C', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_usado_C')),
                ('espacio_usado_D', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_usado_D')),
                ('espacio_disponible_C', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_disponible_C')),
                ('espacio_disponible_D', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_disponible_D')),
                ('AnyDesk_instalado', models.CharField(blank=True, max_length=256, null=True, verbose_name='any_instalado')),
                ('id_AnyDesk', models.CharField(blank=True, max_length=256, null=True, verbose_name='any_instalado')),
            ],
            options={
                'verbose_name': 'computadora',
                'verbose_name_plural': 'computadoras',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='id_perfil')),
                ('descripcion', models.CharField(max_length=256, verbose_name='descripción perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_provincia')),
                ('descripcion', models.CharField(max_length=256, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
            },
        ),
        migrations.AlterModelOptions(
            name='farmacia',
            options={'verbose_name': 'Farmacia', 'verbose_name_plural': 'Farmacias'},
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='id_usuario')),
                ('nombre', models.CharField(max_length=256, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=256, verbose_name='apellido')),
                ('usuario', models.CharField(max_length=256, verbose_name='usuario')),
                ('baja', models.BooleanField(default=True, verbose_name='usuario dado de baja si/no')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.perfil')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_localidad')),
                ('descripcion', models.CharField(max_length=256, verbose_name='descripcion')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.provincia')),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Fcia',
            fields=[
                ('id_farmacia', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_farmacia')),
                ('nombre_facia', models.CharField(max_length=256, verbose_name='nombre_farmacia')),
                ('direccion', models.CharField(max_length=256, verbose_name='direccion')),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.localidad')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.pc_farmacia')),
            ],
            options={
                'verbose_name': 'Fcia',
                'verbose_name_plural': 'Fcias',
            },
        ),
    ]
